language: perl

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y librdf-perl
install:
  - "cpanm --quiet --installdeps --notest RDF::Trine"
  - "cpanm --quiet --installdeps --notest RDF::Query"
  - "cpanm --quiet --notest Module::Install::AuthorTests"
  - "cpanm --quiet --notest IRI"
  - "cpanm --quiet --notest URI::Namespace"
  - "cpanm --quiet --notest DBD::Pg"
  - "cpanm --quiet --notest Moo"
  - "cpanm --quiet --notest Type::Tiny"
  - "cpanm --quiet --notest Math::Cartesian::Product"
  - "cpanm --quiet --notest Test::Roo"
  - "cpanm --quiet --notest Test::LWP::UserAgent"
env:
  - RDFTRINE_STORE_PG_DATABASE="travis_ci_test" RDFTRINE_STORE_PG_MODEL="testmodel"
script:
  - "perl Makefile.PL && make test"
